config/routes.rb
Dwp::Application.routes.draw do
  match "picture/destroy/:id" => "picture#destroy", :as => "picture_destroy"
  match "picture/destroy/" => "picture#destroy", :as => "picture_destroy_template"

  get "photoset/new"
  post "photoset/create"
  get "photoset/destroy"
  get "photoset/manage/:id" => "photoset#manage", :as => "manage_photoset"
  post "photoset/handle_upload/:id" => "photoset#handle_upload", :as => "photoset_handle_upload"
  match "photoset/bundle/:id" => "photoset#bundle", :as => "photoset_bundle"
  get "photoset/rebundle/:id" => "photoset#rebundle", :as => "photoset_rebundle"
  get "bundle/view/:id" => "bundle#view", :as => "bundle"
  get "bundle/ply_as_asc/:id/:bundler_file_id" => "bundle#ply_as_asc", :as => "ply_as_asc"
  get "bundle/ply/:id/:bundler_file_id" => "bundle#ply", :as => "ply"

  get "user/index"

  get "user_sessions/new", :as => "new_user_session"
  get "user_sessions/create"
  post "user_sessions/create", :as => "user_session"
  get "user/index", :as => "user_home"
  get "user_sessions/destroy", :as => "destroy_user_session"

  get "welcome/index", :as => "welcome"

  root :to => "welcome#index"

end

app/controllers/bundle_controller.rb
class BundleController < ApplicationController
  before_filter :require_user
  before_filter :require_bundle

  def view
    @bundle_plys = @bundle.bundler_files.all.find_all { |bf| File.extname(bf.name) == ".ply" }
    if @bundle_plys.empty? then
      flash[:error] = "No points file found for Bundle #{@bundle.id}."
      redirect_to manage_photoset_url(@bundle.photoset)
      return
    end
  end

  def ply_as_asc
    begin
      bf = @bundle.bundler_files.find(params[:bundler_file_id])
    rescue
      render :text => "No PLY file #{params[:bundler_file_id]} found for Bundle #{@bundle.id}."
      return
    end

    self.response_body = proc { |response, output|
      # Generate ASC from PLY
      at_data = false
      File.open(bf.file.path) { |f|
        f.each { |line|
          line.chomp!
          if line == "end_header" then
            at_data = true
            next
          end
          next unless at_data
          fields = line.split(/ /)
          # Convert XYZ NX NY NZ RGB to XYZ RGB NX NY NZ
          outline = [ fields[0], fields[1], fields[2], fields[6], fields[7], fields[8], fields[3], fields[4], fields[5] ].join(" ")
          output.write outline + $/
          # XXX: Does this actually stream content?
        }
      }
    }
  end
  def ply
    begin
      bf = @bundle.bundler_files.find(params[:bundler_file_id])
    rescue
      render :text => "No PLY file #{params[:bundler_file_id]} found for Bundle #{@bundle.id}."
      return
    end

    send_file bf.file.path, :disposition => "inline", :type => "text/plain"
  end
  private
  def require_bundle
    begin
      @bundle = BundlerBundle.find_by_id(params[:id])
      @bundle = nil unless @bundle.photoset.user_id = current_user.id
    rescue
    ensure
      unless @bundle then
        flash[:warning] = "Couldn't find bundle by ID #{params[:id]} for user #{current_user.id}"
        redirect_to user_home_url
      end
    end
  end
end

app/views/bundle/view.html.erb
Drag to rotate; zooming and panning not yet implemented.<br/>
(Apologies, this uses XB-PointStream, which currently supports Chrome, Firefox, and development versions of Safari and Opera only.)

<script type="text/javascript">

  var PSView = Class.create({
    ps: null,
    position: null,
    initialize: function(ply_file, canvas_container) {
      this.position = new PSView.Position();
      var a_canvas = new Element('canvas', {'width': '500', 'height': '300'});
      canvas_container.insert(a_canvas);
      this.ps = new PointStream();

      this.ps.setup(a_canvas, PSView.renderFunction.bind(this));
      this.ps.background([0, 0, 0, 1.0]);
      this.ps.pointSize(0.2);
      this.ps.loadFile({path: ply_file });

      a_canvas.observe('mousedown', PSView.dragStartFunction.bind(this));
      PSView.firstRunInit();
    }
  });
  Object.extend(PSView, {
    Position: Class.create({ x: 0, y: 0, rotX: 0, rotY: 0 }),
    runYet: false,
    firstRunInit: function() {
      if (!PSView.runYet) {
        Event.observe(document.body, 'mouseup', PSView.dragStopFunction);
        PSView.runYet = true;
      }
    },
    dragTracking: new Hash(),
    dragContinueFunction: function(e) {
      PSView.dragTracking.set('mouseX', e.pointerX());
      PSView.dragTracking.set('mouseY', e.pointerY());
    },
    dragStartFunction: function(e) {
      if (e.isLeftClick()) {
        PSView.dragTracking.set('dragging', true);
      } else {
        PSView.dragTracking.set('moving', true);
      }
      PSView.dragTracking.set('element', this);
      PSView.dragTracking.set('startX', e.pointerX());
      PSView.dragTracking.set('startY', e.pointerY());
      PSView.dragTracking.set('mouseX', e.pointerX());
      PSView.dragTracking.set('mouseY', e.pointerY());
      document.body.observe('mousemove', PSView.dragContinueFunction);
      e.stop();
    },
    dragStopFunction: function(e) {
      PSView.dragTracking.unset('element');
      PSView.dragTracking.unset('dragging');
      PSView.dragTracking.unset('moving');
      document.body.stopObserving('mousemove', PSView.dragContinueFunction);
      e.stop();
    },
    renderFunction: function() {
      var zoomed = -1;


      if (PSView.dragTracking.get('element') == this) {
        var deltaX = PSView.dragTracking.get('mouseX') - PSView.dragTracking.get('startX');
        var deltaY = PSView.dragTracking.get('mouseY') - PSView.dragTracking.get('startY');
        PSView.dragTracking.set('startX', PSView.dragTracking.get('mouseX'));
        PSView.dragTracking.set('startY', PSView.dragTracking.get('mouseY'));
        if (PSView.dragTracking.get('dragging')) {
          this.position.rotY += deltaX / this.ps.width * 5;
          this.position.rotX += deltaY / this.ps.height * 5;
        } else if (PSView.dragTracking.get('moving')) {
          this.position.x += deltaX / this.ps.width * 5;
          this.position.y += deltaY / this.ps.height * 5;
        }
      }
      $('debug').innerHTML = "DeltaX: " + deltaX + ", DeltaY: " + deltaY + ", RotX: " + this.position.rotX + ", RotY: " + this.position.rotY;
      $('debug').innerHTML += ", MovX: " + this.position.x + ", MovY: " + this.position.y;

      // Recenter at origin
      this.ps.translate(0, 0, zoomed);

      // Rotate
      this.ps.rotateX(this.position.rotX);
      this.ps.rotateY(this.position.rotY);

      // Recenter on center of rotated object
      if (this.ps.file != undefined) {
        // Recenter on the actual object
        var c = this.ps.file.getCenter();
        this.ps.translate(-c[0],-c[1],-c[2]-1);
      }


      //this.ps.translate(this.position.x, this.position.y, zoomed);
      //$('debug').innerHTML = this.ps.file.getPointCount() + " points @ " + Math.floor(this.ps.frameRate) + " FPS";

      // redraw
      this.ps.clear();
      this.ps.render();
    }
  });
  function initViews() {
    var render;
    <% @bundle_plys.each do |bundle_ply| %>
      // View of <%= bundle_ply.name %>
      var psv = new PSView('<%= escape_javascript(ply_url(:id => @bundle.id, :bundler_file_id => bundle_ply.id)) %>', $('views'));
    <% end %>
  }

</script>
<div id="views"></div>

<span id="debug"></span>
<script type="text/javascript">
  Event.observe(window, 'load', initViews);
</script>