config/routes.rb
Dwp::Application.routes.draw do
  match "picture/destroy/:id" => "picture#destroy", :as => "picture_destroy"
  match "picture/destroy/" => "picture#destroy", :as => "picture_destroy_template"

  get "photoset/new"
  post "photoset/create"
  get "photoset/destroy"
  get "photoset/manage/:id" => "photoset#manage", :as => "manage_photoset"
  post "photoset/handle_upload/:id" => "photoset#handle_upload", :as => "photoset_handle_upload"
  match "photoset/bundle/:id" => "photoset#bundle", :as => "photoset_bundle"
  get "photoset/rebundle/:id" => "photoset#rebundle", :as => "photoset_rebundle"
  get "bundle/view/:id" => "bundle#view", :as => "bundle"
  get "bundle/ply_as_asc/:id/:bundler_file_id" => "bundle#ply_as_asc", :as => "ply_as_asc"
  get "bundle/ply/:id/:bundler_file_id" => "bundle#ply", :as => "ply"

  get "user/index"

  get "user_sessions/new", :as => "new_user_session"
  get "user_sessions/create"
  post "user_sessions/create", :as => "user_session"
  get "user/index", :as => "user_home"
  get "user_sessions/destroy", :as => "destroy_user_session"

  get "welcome/index", :as => "welcome"

  root :to => "welcome#index"

end

app/models/photoset.rb
class Photoset < ActiveRecord::Base
  has_many :pictures, :dependent => :destroy
  has_many :bundler_bundles, :dependent => :destroy
  belongs_to :user

  def can_bundle?
    self.pictures.all.size > 1 && self.pictures.all.find {|pic| pic.processed_image_processing }.nil?
  end
end

app/controllers/photoset_controller.rb
class PhotosetController < ApplicationController
  before_filter :require_user
  before_filter :require_photoset, :except => [ :new, :create, :handle_upload, :rebundle ]
  def new
    @photoset = Photoset.new(:user => current_user)
  end

  def create
    @photoset = Photoset.new(params[:photoset])
    @photoset.user = current_user # Nice try
    if @photoset.save
      flash[:notice] = "Photoset created"
      redirect_to manage_photoset_url(@photoset)
    else
      render :action => :new
    end
  end

  def destroy
    if @photoset.user == current_user then
      @photoset.destroy
      flash[:notice] = "Photoset removed"
    else
      flash[:warning] = "Photoset not removed"
    end
      redirect_to user_home_url
  end

  def manage
    # @photoset is set in :require_photoset
    @bundles = @photoset.bundler_bundles
    @can_write = (current_user == @photoset.user)
    @running_bundles = Delayed::Job.all.find_all { |dj|
        payload = dj.payload_object.respond_to?(:object) && dj.payload_object.object
        payload.is_a?(BundlerController) && @bundles.include?(payload.bundle)
    }.map { |dj| { :bundle => dj.payload_object.object.bundle, :run_at => dj.run_at } }
  end

  def handle_upload
    begin
      @photoset = Photoset.find_by_id_and_user_id(params[:id], current_user.id)
    rescue
      @response = "Couldn't find photoset by ID #{params[:id]} for user #{current_user.id}"
    end
    unless @photoset then
      @response = "Couldn't find photoset by ID #{params[:id]} for user #{current_user.id}"
    end

    if @photoset then
      @picture = Picture.new(params[:picture])
      @picture.name = @picture.image_file_name
      @picture.user = current_user
      @picture.photoset = @photoset
      if @picture.save then
        @success = true
        @response = ""
        @image_thumb = @picture.image.url(:small_cropped)
        @image_id = @picture.id
      else
        @success = false
        @response = "Failed to upload #{@picture.name}"
      end
    else
      @success = false
    end

    @identity = params[:identity]
    render :layout => false
  end
  def rebundle
    bundle = nil
    begin
      bundle = BundlerBundle.find(params[:id])
      @photoset = Photoset.find_by_id_and_user_id(bundle.photoset_id, current_user.id)
    rescue
    ensure
      if !bundle then
        flash[:warning] = "Couldn't find bundle by ID #{params[:id]} for user #{current_user.id}"
        redirect_to user_home_url
        return
      elsif !@photoset then
        flash[:warning] = "Couldn't find photoset by ID #{bundle.photoset_id} for user #{current_user.id}"
        redirect_to user_home_url
        return
      end
    end

    bundle.controller.delay.run
    redirect_to manage_photoset_url(@photoset)
  end
  def bundle
    # Bundle stuff
    b = BundlerBundle.new(:photoset => @photoset)
    unless b.save then
      flash[:warning] = "Couldn't create a new BundlerBundle for photoset #{@photoset.id}"
      redirect_to user_home_url
      return
    end
    b.controller.delay.run
    flash[:notice] = "Starting bundle of #{@photoset.id}"
    redirect_to manage_photoset_url(@photoset)
  end

  private
  def require_photoset
    begin
      @photoset = Photoset.find_by_id_and_user_id(params[:id], current_user.id) || Photoset.find_by_id_and_public(params[:id], true)
    rescue
    ensure
      unless @photoset then
        flash[:warning] = "Couldn't find photoset by ID #{params[:id]} for user #{current_user.id}"
        redirect_to user_home_url
      end
    end
  end
end

app/helpers/photoset_helper.rb
module PhotosetHelper
end

app/views/photoset/handle_upload.html.erb
<html><head><title>Response</title></head><body>
<script type="text/javascript">
  var elem = window.top.window.document.getElementById("<%= escape_javascript @identity %>");
  if (elem) {
    elem.finishUpload("<%= escape_javascript @identity %>", <%= @success %>, "<%= escape_javascript @response %>", "<%= escape_javascript @image_thumb %>", "<%= escape_javascript @image_id.to_s %>");
  }
</script>
</body></html>

app/views/photoset/manage.html.erb
<script type="text/javascript">
  var ih = new ImageHelper();
  Event.observe(window, "load", function() {
      var doneImages = [ <%= @photoset.pictures.map { |pic| "{ 'id': #{pic.id}, 'url': '#{escape_javascript pic.image.url(:small_cropped)}', 'processing': #{pic.processed_image_processing?} }" }.join(", ") %> ];
      <% if @can_write %>
        PhotosetManager.onloadHandler(
                ih,
                "<%= escape_javascript picture_destroy_template_url + "/" %>",
                "<%= escape_javascript(image_path("ticker/ticker")) %>",
                "<%= escape_javascript(image_path("image_controls/delete.png")) %>",
                "<%= escape_javascript(image_path("image_controls/processed.png")) %>",
                "<%= escape_javascript(image_path("image_controls/processing.png")) %>",
                doneImages
        );
      <% else %>
        PhotosetManager.showReadonlyImages(
          ih,
          "<%= escape_javascript(image_path("ticker/ticker")) %>",
          doneImages
        );
      <% end %>
    });
  // TODO: Occasionally poll to see if processing is done
  //window.document.body.observe('click', markDoneProcessing);
</script>

<h1>Upload a picture</h1>

<p<%= @can_write ? "" : raw(" class=\"disabled\"") %>>Upload at least two pictures (5-10 is more useful) of a subject, and then
wait for the icon in the upper right to change from a little yellow clock to a
little green checkbox for each picture. This takes about 30 seconds per (small)
photo (and you have to reload to see the change), but you can keep uploading
photos while you wait. Once you've uploaded your pictures and they've finished
processing, click "Start bundling" below.</p>

<p<%= @can_write ? "" : raw(" class=\"disabled\"") %>>If you don't have any pictures, download the set <a
  href="/dwp/payphone.tgz">here</a> and try it.</p>

<p<%= @can_write ? "" : raw(" class=\"disabled\"") %>>Clicking the little "X" on a photo will remove it from the set.</p>



<% if @can_write %>
  Uploading photos for: <%= @photoset.name %>
<% end %>
<%= form_for :picture, :url => photoset_handle_upload_url(@photoset), :html => { :target => "upload_frame", :enctype => "multipart/form-data" } do |f| %>
  <ul>
    <li><%= f.label :image %><%= f.file_field :image, :disabled => !@can_write %></li>
  </ul>
  <%= f.submit "Upload!", :disabled => !@can_write %>
<% end %>


<div id="widgets" class="ticker" style="display: none;"></div>
<br clear="both"/>


<h1>Bundles</h1>

<p<%= @can_write ? "" : raw(" class=\"disabled\"") %>>Once you've uploaded your
pictures; click "Start bundling" below. For the demo set of 12 images, it will
take between 2 and 5 minutes to assemble the images into a model. (It's
actually about n!*7 seconds, where n is the number of images). Currently, you
have to reload manually to see if it's done. Once it is done, you can click
"view" next to your bundle to view the generated model.</p>

<p<%= @can_write ? "" : raw(" class=\"disabled\"") %>>If there was an error (or not
enough images), you'll get a message at the top of the page saying "No points
file found for Bundle X". In this case, upload more images of the subject and
click "re-bundle".</p>


<ul>
  <% @bundles.each do |b| %>
    <li>
      Bundle: <%= b.id %> (<%= b.updated_at %>)
      <% if (running_bundle = @running_bundles.find { |rb| rb[:bundle] == (b) }) then %>
        <% if running_bundle[:run_at] then %>
          (started at <%= running_bundle[:run_at] %>)
        <% else %>
          (queued)
        <% end %>
      <% else %>
        <% if @can_write %>
          <%= link_to "re-bundle", photoset_rebundle_url(b) %>
        <% end %>
        <%= link_to "view", bundle_url(b) %>
      <% end %>
    </li>
  <% end %>
</ul>
<% if @can_write %>
  <%= link_to_if @photoset.can_bundle?, "Start bundling", photoset_bundle_url %>
<% end %>


<iframe id="upload_frame" name="upload_frame" src="#" style="display:none;"></iframe>

app/views/photoset/new.html.erb
<h1>New Photoset</h1>
<% form_for @photoset, :url => photoset_create_url do |f| %>
  <%= f.error_messages %>

  <%= f.label :name %><br/>
  <%= f.text_field :name %><br/>
  <br/>

  <%= f.label :description %><br/>
  <%= f.text_area :description %><br/>
  <br/>

  <%= f.submit "Create" %>
<% end %>