config/routes.rb
Dwp::Application.routes.draw do
  match "picture/destroy/:id" => "picture#destroy", :as => "picture_destroy"
  match "picture/destroy/" => "picture#destroy", :as => "picture_destroy_template"

  get "photoset/new"
  post "photoset/create"
  get "photoset/destroy"
  get "photoset/manage/:id" => "photoset#manage", :as => "manage_photoset"
  post "photoset/handle_upload/:id" => "photoset#handle_upload", :as => "photoset_handle_upload"
  match "photoset/bundle/:id" => "photoset#bundle", :as => "photoset_bundle"
  get "photoset/rebundle/:id" => "photoset#rebundle", :as => "photoset_rebundle"
  get "bundle/view/:id" => "bundle#view", :as => "bundle"
  get "bundle/ply_as_asc/:id/:bundler_file_id" => "bundle#ply_as_asc", :as => "ply_as_asc"
  get "bundle/ply/:id/:bundler_file_id" => "bundle#ply", :as => "ply"

  get "user/index"

  get "user_sessions/new", :as => "new_user_session"
  get "user_sessions/create"
  post "user_sessions/create", :as => "user_session"
  get "user/index", :as => "user_home"
  get "user_sessions/destroy", :as => "destroy_user_session"

  get "welcome/index", :as => "welcome"

  root :to => "welcome#index"

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :photos
  has_many :photosets

  acts_as_authentic

  def guest?
    return self.login == "guest"
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_filter :require_user
  def index
    @photosets = current_user.photosets
    @public_photosets = Photoset.find_all_by_public(true) - @photosets
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/user/index.html.erb
<h1>Photosets</h1>
<ul>
  <%= link_to "New", photoset_new_url %>
  <h2>Your photosets:</h2>
  <% @photosets.each do |set| %>
  <li><%= link_to set.name, manage_photoset_url(set) %> - <%= set.pictures.size %> pictures</li>
  <% end %>
  <h2>Public photosets:</h2>
  <% @public_photosets.each do |set| %>
  <li><%= link_to set.name, manage_photoset_url(set) %> - <%= set.pictures.size %> pictures</li>
  <% end %>
</ul>